(() => {
  if(window.DBT_FLEX_SAFETY_V1)return;window.DBT_FLEX_SAFETY_V1=true;
  let socket=null,state=null,target=null,bound=false,timer=0,toastTimer=0;
  const session=()=>{try{const s=JSON.parse(localStorage.getItem('flex-session')||'null');return s?.roomCode&&s?.token?s:null}catch{return null}};
  const toast=text=>{const el=document.getElementById('toast');if(el){el.textContent=text;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,2800)}};
  const dialog=document.createElement('dialog');dialog.className='dbt-flex-safety';dialog.innerHTML='<div class="dbt-fs-head"><div><small>DBT GAMES · FLEX SAFETY</small><b>Report a player</b></div><button class="dbt-fs-close" type="button">✕</button></div><div class="dbt-fs-body"><div class="dbt-fs-note">Reports are room-scoped, rate-limited and tied to your current Flex session. This panel never changes cards, turns, challenges or match results. For voice, you can also mute any peer locally in Voice Room.</div><div class="dbt-fs-list" data-list></div><div class="dbt-fs-form" data-form hidden><b data-title>Report player</b><select data-reason><option value="harassment">Harassment / bullying</option><option value="spam">Spam / disruptive behavior</option><option value="hate">Hate or hateful conduct</option><option value="sexual">Sexual content</option><option value="threats">Threats / intimidation</option><option value="cheating">Cheating / exploit suspicion</option><option value="voice">Voice-room abuse</option><option value="other">Other</option></select><textarea data-note maxlength="180" placeholder="Optional note (max 180 characters)"></textarea><div class="dbt-fs-actions"><button data-cancel type="button">CANCEL</button><button data-submit type="button">SUBMIT REPORT</button></div></div></div>';document.body.appendChild(dialog);
  const q=s=>dialog.querySelector(s);
  function render(){const box=q('[data-list]');box.replaceChildren();const s=session();const players=(state?.players||[]).filter(p=>!p.isBot&&p.token!==s?.token);if(!players.length){const x=document.createElement('div');x.className='dbt-fs-empty';x.textContent='Other human Flex players will appear here after you join a room.';box.appendChild(x);return}for(const p of players){const row=document.createElement('div');row.className='dbt-fs-player';const copy=document.createElement('div');const b=document.createElement('b');b.textContent=`${p.avatar||'🎮'} ${p.name}`;const sm=document.createElement('small');sm.textContent=p.connected?'Connected Flex player':'Currently reconnecting';copy.append(b,sm);const btn=document.createElement('button');btn.type='button';btn.textContent='REPORT';btn.onclick=()=>{target=p;q('[data-title]').textContent=`Report ${p.name}`;q('[data-note]').value='';q('[data-form]').hidden=false;q('[data-reason]').focus()};row.append(copy,btn);box.appendChild(row)}}
  function mount(){if(document.getElementById('dbt-flex-safety-open'))return;const anchor=document.querySelector('.flex-top')||document.querySelector('.top')||document.getElementById('lobby');if(!anchor)return;const btn=document.createElement('button');btn.id='dbt-flex-safety-open';btn.type='button';btn.textContent='🛡 SAFETY';btn.onclick=()=>{render();dialog.showModal()};anchor.appendChild(btn)}
  function bind(){if(bound)return true;socket=window.DBT_FLEX_SOCKET;if(!socket?.on)return false;bound=true;socket.on('f_state',s=>{state=s;if(dialog.open)render()});socket.on('fs_ack',d=>{q('[data-form]').hidden=true;target=null;toast(`Report submitted for ${d?.target||'player'} ✅`)});socket.on('fs_error',d=>toast(d?.message||'Report could not be submitted.'));return true}
  q('.dbt-fs-close').onclick=()=>dialog.close();q('[data-cancel]').onclick=()=>{q('[data-form]').hidden=true;target=null};q('[data-submit]').onclick=()=>{const s=session();if(!s||!socket?.connected||!target)return toast('Flex report connection unavailable.');socket.emit('fs_report',{sessionToken:s.token,targetToken:target.token,reason:q('[data-reason]').value,note:q('[data-note]').value.trim()})};
  timer=setInterval(()=>{mount();bind()},800);window.addEventListener('beforeunload',()=>clearInterval(timer),{once:true});mount();bind();window.DBT_FLEX_SAFETY={open:()=>{render();dialog.showModal()}};
})();